import AchievementModel from "../models/Achievement.js";

export const achievements = [
  {
    achievementId: "first-quiz",
    title: "Langkah Pertama",
    description: "Selesaikan quiz pertamamu",
    icon: "🎯",
    category: "beginner",
    xpReward: 50,
    gemsReward: 10,
    conditionType: "quiz_count",
    conditionValue: 1,
  },
  {
    achievementId: "first-module",
    title: "Modul Pertama",
    description: "Selesaikan modul pertamamu",
    icon: "📚",
    category: "beginner",
    xpReward: 75,
    gemsReward: 15,
    conditionType: "module_count",
    conditionValue: 1,
  },
  {
    achievementId: "streak-3",
    title: "Konsisten 3 Hari",
    description: "Belajar 3 hari berturut-turut",
    icon: "🔥",
    category: "streak",
    xpReward: 75,
    gemsReward: 10,
    conditionType: "streak",
    conditionValue: 3,
  },
  {
    achievementId: "streak-7",
    title: "Semangat 7 Hari",
    description: "Belajar 7 hari berturut-turut",
    icon: "🔥",
    category: "streak",
    xpReward: 100,
    gemsReward: 20,
    conditionType: "streak",
    conditionValue: 7,
  },
  {
    achievementId: "streak-14",
    title: "Dua Minggu Konsisten",
    description: "Belajar 14 hari berturut-turut",
    icon: "🔥",
    category: "streak",
    xpReward: 200,
    gemsReward: 40,
    conditionType: "streak",
    conditionValue: 14,
  },
  {
    achievementId: "streak-30",
    title: "Sebulan Tanpa Henti",
    description: "Belajar 30 hari berturut-turut",
    icon: "🔥",
    category: "streak",
    xpReward: 500,
    gemsReward: 100,
    conditionType: "streak",
    conditionValue: 30,
  },
  {
    achievementId: "perfect-score",
    title: "Sempurna!",
    description: "Dapatkan skor 100% dalam quiz",
    icon: "⭐",
    category: "mastery",
    xpReward: 150,
    gemsReward: 25,
    conditionType: "perfect_quiz_count",
    conditionValue: 1,
  },
  {
    achievementId: "early-bird",
    title: "Si Pagi",
    description: "Belajar sebelum jam 8 pagi",
    icon: "🌅",
    category: "special",
    xpReward: 75,
    gemsReward: 15,
    conditionType: "early_morning_session",
    conditionValue: 1,
  },
  {
    achievementId: "night-owl",
    title: "Burung Hantu",
    description: "Belajar setelah jam 10 malam",
    icon: "🦉",
    category: "special",
    xpReward: 75,
    gemsReward: 15,
    conditionType: "late_night_session",
    conditionValue: 1,
  },
  {
    achievementId: "speed-demon",
    title: "Kilat Cepat",
    description: "Selesaikan 5 soal dalam 2 menit",
    icon: "⚡",
    category: "speed",
    xpReward: 120,
    gemsReward: 20,
    conditionType: "speed_record",
    conditionValue: 1,
  },
  {
    achievementId: "master-algebra",
    title: "Master Aljabar",
    description: "Capai 90% penguasaan Aljabar",
    icon: "🎓",
    category: "mastery",
    xpReward: 200,
    gemsReward: 50,
    conditionType: "category_mastery_algebra",
    conditionValue: 90,
  },
  {
    achievementId: "master-geometry",
    title: "Master Geometri",
    description: "Capai 90% penguasaan Geometri",
    icon: "📐",
    category: "mastery",
    xpReward: 200,
    gemsReward: 50,
    conditionType: "category_mastery_geometry",
    conditionValue: 90,
  },
  {
    achievementId: "master-statistics",
    title: "Master Statistika",
    description: "Capai 90% penguasaan Statistika",
    icon: "📊",
    category: "mastery",
    xpReward: 200,
    gemsReward: 50,
    conditionType: "category_mastery_statistics",
    conditionValue: 90,
  },
  {
    achievementId: "social-butterfly",
    title: "Kupu-Kupu Sosial",
    description: "Bantu 3 teman dengan peer tutoring",
    icon: "🦋",
    category: "social",
    xpReward: 150,
    gemsReward: 30,
    conditionType: "helped_students",
    conditionValue: 3,
  },
  {
    achievementId: "comeback-kid",
    title: "Bangkit Kembali",
    description: "Tingkatkan skor dari 50% ke 80%",
    icon: "📈",
    category: "improvement",
    xpReward: 200,
    gemsReward: 40,
    conditionType: "score_improvement",
    conditionValue: 30,
  },
  {
    achievementId: "quiz-master",
    title: "Quiz Master",
    description: "Selesaikan 50 quiz",
    icon: "🏆",
    category: "volume",
    xpReward: 300,
    gemsReward: 60,
    conditionType: "quiz_count",
    conditionValue: 50,
  },
  {
    achievementId: "module-master",
    title: "Pembelajar Sejati",
    description: "Selesaikan 10 modul pembelajaran",
    icon: "📚",
    category: "volume",
    xpReward: 400,
    gemsReward: 80,
    conditionType: "module_count",
    conditionValue: 10,
  },
  {
    achievementId: "xp-1000",
    title: "Ribu Pertama",
    description: "Kumpulkan 1000 XP",
    icon: "💎",
    category: "milestone",
    xpReward: 100,
    gemsReward: 25,
    conditionType: "total_xp",
    conditionValue: 1000,
  },
  {
    achievementId: "xp-5000",
    title: "Lima Ribu",
    description: "Kumpulkan 5000 XP",
    icon: "💎",
    category: "milestone",
    xpReward: 250,
    gemsReward: 50,
    conditionType: "total_xp",
    conditionValue: 5000,
  },
  {
    achievementId: "xp-10000",
    title: "Sepuluh Ribu!",
    description: "Kumpulkan 10000 XP",
    icon: "💎",
    category: "milestone",
    xpReward: 500,
    gemsReward: 100,
    conditionType: "total_xp",
    conditionValue: 10000,
  },
];

export async function seedAchievements() {
  try {
    console.log("🏆 Seeding achievements...");
    
    // Clear existing achievements
    await AchievementModel.deleteMany({});
    
    // Insert new achievements
    const result = await AchievementModel.insertMany(achievements);
    
    console.log(`✅ Successfully seeded ${result.length} achievements`);
    return result;
  } catch (error) {
    console.error("❌ Error seeding achievements:", error);
    throw error;
  }
}
